### ISSUE TITLE
Not work "- yarn seed"

### ISSUE THREAD

**Issue by tereshchuk** [stelace/stelace#617] opened 2021-03-24 11:30 UTC
Hi, guys.

I have a problem. I am trying to execute - yarn seed - but it stays in place and does not add keys. Tell me what can I do to make it work ??
redis - works.
Maybe there is an opportunity to view the logs - yarn seed?

It just hangs what is on the screen and does not load further
![Снимок экрана (333)](https://user-images.githubusercontent.com/23060142/112303096-91963e80-8ca4-11eb-9de5-f9c9857e418d.png)

p.s Guys, sorry for the stupid questions. But I am a beginner and want to use Stelace as it is interesting.

brothers help me @abruere @woyuen @justinschuldt

**Comment by abruere** [comment] 2021-03-24 12:42
Hi, it looks like an issue with Windows again. As mentioned in this other [issue (468)](https://github.com/stelace/stelace/issues/468) you created, we will accept any contribution to improve compatibility but given our limited resources we focus on UNIX environment.

Again, docker is the way to go.
But please note that Stelace is probably not the right project to learn back-end ! There are too many moving parts.

Closing this as a duplicate of https://github.com/stelace/stelace/issues/468 for now.

**Comment by tereshchuk** [comment] 2021-03-24 12:48
> Hi, it looks like an issue with Windows again. As mentioned in this other [issue (468)](https://github.com/stelace/stelace/issues/468) you created, we will accept any contribution to improve compatibility but given our limited resources we focus on UNIX environment.
> 
> Again, docker is the way to go.
> But please note that Stelace is probably not the right project to learn back-end ! There are too many moving parts.
> 
> Closing this as a duplicate of #468 for now.

I am currently using Linux Ubuntu on a server. I rented a VPS. I am not using Windows.

**Comment by abruere** [comment] 2021-03-24 20:51
Then, as discussed in #468, please ensure databases are up and running, and check that the server can reach them.

**Comment by woyuen** [comment] 2021-03-25 06:42
@tereshchuk To view the logs during the seed, you can add an environment variable:
```sh
ROARR_LOG=true yarn seed
```

**Comment by justinschuldt** [comment] 2021-03-25 07:54
I actually also ran into issues running `yarn seed` when I was first testing the platform.

Here is what I did to get it working:

- update [./knexfile.js](https://github.com/stelace/stelace/blob/dev/knexfile.js) to include the path to the migration files, and the DB schema for the seed data. Complete knexfile.js should be:
```javascript
require('dotenv').config()

module.exports = {

  client: 'pg',
  connection: {
    host: process.env.POSTGRES_HOST,
    database: process.env.POSTGRES_DB,
    user: process.env.POSTGRES_USER,
    password: process.env.POSTGRES_PASSWORD,
    port: process.env.POSTGRES_PORT,
    schema: 's1_test'
  },
  migrations: {
    directory: './migrations/knex',
    tableName: 'knex_migrations'
  }

}

```
- run `yarn knex migrate:latest`
- run `yarn seed`

I didn't send a PR because I am unsure if the knexfile.js is used for anything else besides migrating. Seems like the schema only needs to be added to the knexfile for migrating via the yarn command, as opposed to initializing a platform via the REST api, which I assume also runs the migrations somehow.

Also, FWIW, I ended up just creating api keys and roles via the REST api, then seeding data from the marketplace-demo. You will probably want to do the same @tereshchuk. Don't have your backend that is live to the whole world use API keys from `yarn seed`, as they are hardcoded, your platform will not be secure.

**Comment by justinschuldt** [comment] 2021-03-25 08:09
FWIW, in the spirit of paying it forward with all the time I saved by getting Stelace working for my project:

Ultimately I found it better to stand up Stelace with an empty DB then use REST apis to create the platform, initialize it, create roles, and finally API keys, so that I could then use one of the frontend examples ([marketplace-demo](https://github.com/stelace/marketplace-demo)) to seed data.

Here is how I got setup, I sent the API calls from [Insomnia REST client](https://insomnia.rest/products/insomnia) (similar to Postman):

- POST /store/platforms
- POST /store/platforms/:patformId/init
- POST /store/platforms/:patformId/cache/sync
- POST /roles (dev, public, user, provider, org, premium)
- POST /api-keys (secret keys first, by changing [this](https://github.com/stelace/stelace/blob/dev/src/services/apiKey.js#L182), then public keys)
- then using the newly generated API keys ^, you can seed data from the [marketplace-demo](https://github.com/stelace/marketplace-demo#getting-started)

Good luck!

If you're interested @abruere & @woyuen, I could send a PR to include my Insomnia environment in a subfolder in this repo, so that people could import the collection of API calls to help get up and running. Not sure if that aligns with your vision for bootstrapping a platform.

**Comment by tereshchuk** [comment] 2021-03-25 10:45
> Then, as discussed in #468, please ensure databases are up and running, and check that the server can reach them.

![Снимок экрана (334)](https://user-images.githubusercontent.com/23060142/112460808-f6669d00-8d67-11eb-8a78-b19a5930c312.png)

**Comment by tereshchuk** [comment] 2021-03-25 10:47
> На самом деле я также столкнулся с проблемами, `yarn seed`когда впервые тестировал платформу.
> 
> Вот что я сделал, чтобы он заработал:
> 
> * обновите [./knexfile.js,](https://github.com/stelace/stelace/blob/dev/knexfile.js) чтобы включить путь к файлам миграции и схему БД для исходных данных. Полный knexfile.js должен быть:
> 
> ```js
> требовать ( 'dotenv' ) . config ( )
> 
> модуль . экспорт  =  {
> 
>   клиент : 'pg' , 
>   соединение : { 
>     хост : процесс . окр . POSTGRES_HOST , 
>     база данных : процесс . окр . POSTGRES_DB , 
>     пользователь : процесс . окр . POSTGRES_USER , 
>     пароль : процесс . окр . POSTGRES_PASSWORD , 
>     порт : процесс . окр . POSTGRES_PORT , 
>     схема :'s1_test' 
>   } , 
>   миграции : { 
>     каталог : './migrations/knex' , 
>     tableName : 'knex_migrations' 
>   }
> 
> }
> ```
> 
> * пробег `yarn knex migrate:latest`
> * пробег `yarn seed`
> 
> Я не отправлял PR, потому что не уверен, используется ли knexfile.js для чего-то еще, кроме миграции. Похоже, что схему нужно только добавить в knexfile для миграции с помощью команды yarn, в отличие от инициализации платформы через REST api, который, как я полагаю, также каким-то образом запускает миграции.
> 
> Кроме того, FWIW, я закончил тем, что просто создал ключи и роли api через REST api, а затем загрузил данные из демо-версии Marketplace. Вероятно, вы захотите сделать то же самое @tereshchuk . У вас нет бэкэнда, который доступен для всего мира, используйте ключи API `yarn seed`, так как они жестко запрограммированы, ваша платформа не будет защищена.

Did as you wrote, the result showed many errors.

**Comment by tereshchuk** [comment] 2021-03-25 10:48
> I actually also ran into issues running `yarn seed` when I was first testing the platform.
> 
> Here is what I did to get it working:
> 
> * update [./knexfile.js](https://github.com/stelace/stelace/blob/dev/knexfile.js) to include the path to the migration files, and the DB schema for the seed data. Complete knexfile.js should be:
> 
> ```js
> require('dotenv').config()
> 
> module.exports = {
> 
>   client: 'pg',
>   connection: {
>     host: process.env.POSTGRES_HOST,
>     database: process.env.POSTGRES_DB,
>     user: process.env.POSTGRES_USER,
>     password: process.env.POSTGRES_PASSWORD,
>     port: process.env.POSTGRES_PORT,
>     schema: 's1_test'
>   },
>   migrations: {
>     directory: './migrations/knex',
>     tableName: 'knex_migrations'
>   }
> 
> }
> ```
> 
> * run `yarn knex migrate:latest`
> * run `yarn seed`
> 
> I didn't send a PR because I am unsure if the knexfile.js is used for anything else besides migrating. Seems like the schema only needs to be added to the knexfile for migrating via the yarn command, as opposed to initializing a platform via the REST api, which I assume also runs the migrations somehow.
> 
> Also, FWIW, I ended up just creating api keys and roles via the REST api, then seeding data from the marketplace-demo. You will probably want to do the same @tereshchuk. Don't have your backend that is live to the whole world use API keys from `yarn seed`, as they are hardcoded, your platform will not be secure.

Did as you wrote, the result showed many errors.

**Comment by tereshchuk** [comment] 2021-03-27 07:46
@abruere @woyuen So can you help me with this problem?
I still have a problem with the yarn seed

**Comment by woyuen** [comment] 2021-03-29 05:10
@tereshchuk Please can you show us the logs after I suggested you to add the environment variable?
Without them, we can't help you as we don't see your errors.

**Comment by abruere** [comment] 2021-03-29 07:17
@justinschuldt, thank you for your proposal.

Initialization should be even easier : that was the point of `yarn seed`.
We’ll first make sure this works as expected!

Reopening.

**Comment by tereshchuk** [comment] 2021-03-30 08:52
I solved this problem using thanks to - Develop with API server container

**Closed as completed** 2021-03-30 09:06 UTC
